export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const CREATE_EMPLOYEE_DETAILS_SERVER_RESPONSE_SUCCESS =
  "CREATE_EMPLOYEE_DETAILS_SERVER_RESPONSE_SUCCESS";
export const CREATE_EMPLOYEE_DETAILS_SERVER_RESPONSE_ERROR =
  "CREATE_EMPLOYEE_DETAILS_SERVER_RESPONSE_ERROR";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
